### ISSUE TITLE
This project support ios as device target?

### ISSUE THREAD

**Issue by hugoruscitti** [amex4152/cordova-phaser#1]

**Comment by amex4152** [comment]
Hi,

 I'm afraid I have no way to test it, but in theory, you only need to add iOS as platform on cordova-cli, and perhaps remove the crosswalk webview plugin, before the  `cordova prepare`

i.e.

`cordova platform add ios`

Take into account that you need to cover the requeriments of the iOS platform, this means normally that you´re develping on an OSX machine.

**Comment by cfurrow** [comment]
I was able to get it to work by adding the ios platform and then used this repo as a jumping-off point to play with Phaser on ios. Thanks!

**Comment by amex4152** [comment]
Ok, thank you @cfurrow , I'll close this issue and update later the README
